//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.DiplomaOrCertificate = new HashSet<DiplomaOrCertificate>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int ContractID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> PriceID { get; set; }
        public Nullable<int> RequisiteID { get; set; }
        public int FormOfStudyID { get; set; }
        public int StatusContractID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual FormOfStudy FormOfStudy { get; set; }
        public virtual Price Price { get; set; }
        public virtual Requisite Requisite { get; set; }
        public virtual StatusContract StatusContract { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiplomaOrCertificate> DiplomaOrCertificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
