//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplomaOrCertificate
    {
        public int DiplomaOrCertificateID { get; set; }
        public string SeriesDiploma { get; set; }
        public string NumberDiploma { get; set; }
        public string NumberCertificate { get; set; }
        public int ContractID { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
