//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma1._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Dimploma1Entities : DbContext
    {
        private static Dimploma1Entities _context;
        public static Dimploma1Entities GetContext()
        {
            if (_context == null)
            {
                _context = new Dimploma1Entities();
            }
            return _context;
        }
        public Dimploma1Entities()
            : base("name=Dimploma1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appraisal> Appraisal { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<DiplomaOrCertificate> DiplomaOrCertificate { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<DiscountStudent> DiscountStudent { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeRole> EmployeeRole { get; set; }
        public virtual DbSet<FormOfStudy> FormOfStudy { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupStudent> GroupStudent { get; set; }
        public virtual DbSet<InformationSource> InformationSource { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Requisite> Requisite { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<StatusAttendance> StatusAttendance { get; set; }
        public virtual DbSet<StatusContract> StatusContract { get; set; }
        public virtual DbSet<StatusCourse> StatusCourse { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentCourse> StudentCourse { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeacherCourse> TeacherCourse { get; set; }
        public virtual DbSet<TeacherTask> TeacherTask { get; set; }
        public virtual DbSet<Time> Time { get; set; }
        public virtual DbSet<TypeCourse> TypeCourse { get; set; }
        public virtual DbSet<TypeLesson> TypeLesson { get; set; }
    }
}
