//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int ContractID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string Note { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
