//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Price()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int PriceID { get; set; }
        public Nullable<int> PriceQuantity { get; set; }
        public Nullable<bool> PricePerLesson { get; set; }
        public Nullable<System.DateTime> DatePrice { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TypeLessonID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Course Course { get; set; }
        public virtual TypeLesson TypeLesson { get; set; }
    }
}
