//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Attendance = new HashSet<Attendance>();
        }
    
        public int ScheduleID { get; set; }
        public Nullable<System.DateTime> ClassDate { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> TimeID { get; set; }
        public Nullable<int> CabinetID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual Cabinet Cabinet { get; set; }
        public virtual Course Course { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Group Group { get; set; }
        public virtual Student Student { get; set; }
        public virtual Time Time { get; set; }
    }
}
