//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourse
    {
        public int StudentCourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> StatusCourseID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual StatusCourse StatusCourse { get; set; }
        public virtual Student Student { get; set; }
    }
}
